language: c
sudo: required
before_install:
  - sudo apt-get -y install liblapacke-dev libopenblas-dev/
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: 
- bash -ex .travis-opam.sh

env:
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.09
os:
  - linux
  - osx