language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: 
- bash -ex .travis-opam.sh

env:
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.09 POST_INSTALL_HOOK="opam install bisect-ppx; bisect-ppx-report -coveralls coverage.json -service-job-id $TRAVIS_JOB_ID -I _build/default _build/default/test/bisect*.out; curl -L -F json_file=@./coverage.json https://coveralls.io/api/v1/jobs"
os:
  - linux
  - osx