name: "Build and test"
on: [push, pull_request]
jobs:
  osx:
    name: OS X
    runs-on: macos-latest
    strategy:
      matrix:
        ocaml-version: [ '4.11.0', '4.10.0' ]
    steps:
    - uses: actions/checkout@master
    - uses: avsm/setup-ocaml@master
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Locate brew cache
      id: brew-cache
      run: echo "::set-output name=dir::$(brew --cache)/downloads"
    - name: Brew cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.brew-cache.outputs.dir }}
        key: ${{ runner.os }}-brew
    - run: brew install pkg-config openblas
    - run: opam install owl
    - run: opam install -t . --deps-only
    - run: opam list
    - run: GOBBA_EXAMPLES=$(realpath ./examples/) opam exec dune runtest --verbose
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container: sykhro/gobba-deps:latest
    steps:
    - run: source /root/.bash_profile
    - uses: actions/checkout@master
    - run: dnf install zlib-devel -y
    - run: opam init --yes --disable-sandboxing
    - run: opam install --yes owl
    - run: opam install --yes -t . --deps-only
    - run: opam list
    - run: GOBBA_EXAMPLES=$(realpath ./examples/) opam exec dune runtest --verbose
