name: "Build and test"
on: [push, pull_request]
jobs:
  osx:
    name: OS X
    strategy:
      matrix:
        ocaml-version: [ '4.11.0', '4.10.0' ]
        runs-on: [macos-10.15, macos-11.0]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@master
    - uses: avsm/setup-ocaml@master
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Locate brew cache
      id: brew-cache
      run: echo "::set-output name=dir::$(brew --cache)/downloads"
    - name: Brew cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.brew-cache.outputs.dir }}
        key: ${{ runner.os }}-brew
    - run: brew install pkg-config openblas
    - run: opam install owl
    - run: opam install -t . --deps-only
    - run: opam list
    - run: GOBBA_EXAMPLES=$(realpath ./examples/) opam exec dune runtest --verbose
  linux:
    name: Linux
    runs-on: ubuntu-20.04
    container:
      image: sykhro/gobba-deps:latest
    steps:
    - uses: actions/checkout@master
    - run: opam install -yvt . --deps-only
    - run: opam list
    - run: GOBBA_EXAMPLES=$(realpath ./examples/) opam exec dune runtest --verbose
